### ISSUE TITLE
ACC support

### ISSUE THREAD

**Issue by condaatje** [Spacefreak18/monocoque#4]
I'm very interested in promoting ACC support in whichever way is most helpful - I have some experience with C but not much in modding games. From a high level, what might be the starting point and process for a fresh dev to implement support for a new game?

If I can't be helpful in the code, I could at least try to be helpful in writing documentation in this repo

**Comment by condaatje** [comment]
https://www.assettocorsa.net/forum/index.php?threads/acc-shared-memory-documentation.59965/

looks like the devs published some (un?)official map details - maybe somebody has created a plugin

**Comment by condaatje** [comment]
possible viable plugin and reference code(?):

https://github.com/MorGuux/AssettoCorsaCompetizioneSharedMemory

**Comment by Spacefreak18** [comment]
Hi there, 

I'm working on ACC support as we speak.

This actually kind of belongs in the [simapi](https://github.com/Spacefreak18/simapi) project. All the projects i'm working on (simlcd (f1 wheel), gilles (telemetry), and monocoque all use that same library as a submodule. I may at one point make it a DLL.

As far as it all would work, unfortunately the plugin system for Assetto Corsas are a bit different than RFactor. And for some reason I remember thinking about going down that route but sticking with the shared memory bridge approach that I saw others attempting like I've done in [simshmbridge](https://github.com/spacefreak18/simshmbridge). That project maps the shared memory region into and out of wine space, from linux space. And likewise, my goal is to have it work for all sims in one project.

The plugin approach has two downsides as far as I could see, if it's possible. Firstly, it's a little more complex because Assetto Corsa plugins are python, you'd have to access Linux shared memory from a windows python environment, or otherwise load a dll from that python environment, and then write to Linux shared memory space.

The other downside I could see is I'm also successfully using the simshmbridge project for [CrewChief](https://anton2641.gitlab.io/CrewChiefV4/). I like to install that into a completely different wine prefix from what I have for Assetto Corsa or RFactor to avoid any potential compatibility comflicts. So for Assetto Corsa, I map the shared memory from the proton wine prefix Assetto Corsa runs in, into Linux, then back into another wine prefix just for CrewChief. So to use CrewChief with RFactor, the way I am currently, I'd still have to map it's shared memory into the CrewChief wine prefix, despite RFactor writing it's shared memory straight into Linux.

But this is a great discussion, because it is really vital to know other people's workflows to know which features are most important and make this all work as well as possible.

**Comment by condaatje** [comment]
looping back to record that @Spacefreak18 pushed code a few weeks ago that gets ACC working! incredible.
